blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostList.as_view(), name = "post"),
    path('post/', views.PostList.as_view(), name='post'),
    path('post-detail/<pk>', views.PostDetail.as_view(), name='post-detail'),
    path('author', views.AuthorList.as_view(), name='author'),
    path('author-detail/<pk>', views.AuthorDetail.as_view(), name='author-detail'),
]

jblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/posts', views.PostApiList.as_view()),
    path('api/authors',views.AuthorApiList.as_view()),
    path('', include('blog.urls')),
]

urlpatterns =format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns

# Create your models here.

class Post(models.Model):
    post_name = models.CharField(max_length=100, help_text="Enter the post name")
    post_message = models.TextField(max_length=3000, help_text="Enter the post details")
    post_author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    post_img = models.FileField()
    post_date = models.DateField(null=True, blank=True)
    post_highlight = models.TextField(null=True,  max_length=400,
                                      help_text="Highlight of your post e.g Trump, we have to stop rocket man"
                                      )

    def __str__(self):
        return self.post_name

    def get_absolute_url(self):
        return reverse('post-detail', args=[str(self.id)])

    class Meta:
        ordering = ['-post_date']


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    author_img = models.FileField()
    author_description = models.TextField(max_length=200, default="I am an author that live in Nigeria.")

    def __str__(self):
        return '{} {}'.format(self.last_name, self.first_name)

    """
    To get the particular instance of an author
    """

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

blog/views.py
# from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Post, Author
from django.views import generic
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import PostSerializer,AuthorSerializer

# Api views
# api/posts
class PostApiList(APIView):

    def get(self, request):
        posts = Post.objects.all()
        serializer = PostSerializer(posts, many=True)
        return Response(serializer.data)

    def post(self):
        pass

# api/authors
class AuthorApiList(APIView):

    def get(self, request):
        authors = Author.objects.all()
        serializer = AuthorSerializer(authors, many=True)
        return Response(serializer.data)



# Create your views here.

class PostList(generic.ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.all()

    template_name = 'blog/index.html'


class PostDetail(generic.DetailView):
    model = Post
    paginate_by = 10

    template_name = 'blog/post_detail.html'


class AuthorList(generic.ListView):
    model = Author

    def get_queryset(self):
        return Author.objects.all()

    template_name = 'blog/author.html'


class AuthorDetail(generic.DetailView):
    model = Author
    template_name = 'blog/author_detail.html'

templates/blog/author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authors</title>
</head>
<body>
    <h2>Authors</h2>
    {% for author in author_list %}
        <a href="{{ author.get_absolute_url }}"><p>{{ author.first_name }}</p></a>
    {% endfor %}
</body>
</html>

templates/blog/author_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ author.first_name }}</title>
</head>
<body>
    <h4>{{ author.first_name }} {{ author.last_name }}</h4>
    <p>{{ author.date_of_birth }} {% if author.date_of_death %} - {{ author.date_of_death }}{% endif %}</p>
    <img src="{{ author.author_img.url }}">
    <p>{{ author.author_description }}</p>

    <h4>{{ author.first_name }} Posts</h4>
    {% for post in author.post_set.all %}
        <a href="{{ post.get_absolute_url }}">{{ post }}</a>
    {% endfor %}
</body>
</html>

templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home - Jblog</title>
</head>
<body>
    <div class="main">
        <h1>Welcome to Jblog.</h1>
        {% for post in post_list %}
            <img src="{{ post.post_img.url }}" style="width:70px; height: 70px;" alt = "{{ post.post_name }} image">
            <a href = "{{ post.get_absolute_url }}"><p>{{ post.post_name }}</p></a>
            <kbd>{{ post.post_highlight }}</kbd>
            <span>on {{ post.post_date }}</span>
            <a href="{{ post.post_author.get_absolute_url }}"> <p>By {{ post.post_author }}</p></a>

        {% endfor %}
    </div>
</body>
</html>

templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ post.post_name }}</title>
</head>
<body>
    <h3>{{ post.post_name }}</h3>
    <a href="{{ post.post_author.get_absolute_url }}"><span>by {{ post.post_author }}</span></a>
    <span>{{ post.post_date }}</span>
    <br>
    <img src="{{ post.post_img.url }}" style="height: 100px; width: 100px;">
    <p>{{ post.post_message }}</p>
</body>
</html>